#!/usr/bin/env python

import sys, os, re, subprocess as sp
from distutils.core import setup

if not sys.version_info[0] == 3:
    sys.exit("Python 2.x is not supported; Python 3.x is required.")

########################################

# Based on this recipe, adapted for Python 3, Git 2.8.x, and PEP-440 version identifiers
#   http://blogs.nopcode.org/brainstorm/2013/05/20/pragmatic-python-versioning-via-setuptools-and-git-tags/
#   https://www.python.org/dev/peps/pep-0440/#version-scheme

# Fetch version from git tags, and write to version.py.
# Also, when git is not available (PyPi package), use stored version.py.
version_py = os.path.join(os.path.dirname(__file__), 'version.py')

try:
    version_git = sp.check_output(["git", "describe", "--tags"]).strip().decode('ascii')
    final, dev, blob = re.match(r'v?((?:\d+\.)*\d+)(?:-(\d+)-(g[a-z0-9]+))?', version_git).groups()
    version_pep = final+('.dev%s+%s'%(dev,blob) if dev else '')
except sp.CalledProcessError:
    with open(version_py, 'r') as fh:
        version_pep = open(version_py).read().strip().split('=')[-1][1:-1]
else:
    with open(version_py, 'w') as fh:
        print("# Do not edit this file, tetherback versioning is governed by git tags", file=fh)
        print('__version__="%s"\n' % version_pep, file=fh)

########################################

setup(name="tetherback",
      version=version_pep,
      description=("Create backups of an Android device over USB (requires adb and TWRP recovery)"),
      long_description=open('README.md').read(),
      author="Daniel Lenski",
      author_email="dlenski@gmail.com",
      install_requires=[ 'progressbar2>=3.6', 'tabulate' ],
      license='GPL v3 or later',
      url="https://github.com/dlenski/tetherback",
      packages=["tetherback"],
      entry_points={ 'console_scripts': [ 'tetherback=tetherback.__main__:main' ] }
      )
